version: "3"

services:
  # MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - "4000:3000"
    environment:
      - APP_NAME=GroceryBookingApp
      - PORT=3000
      - DB_URI=mongodb://mongo_db:27017/grocery_booking_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
